run:
  timeout: 5m
linters-settings:
  gofmt:
    simplify: true
  staticcheck:
    checks: ["all"]
  errcheck:
    check-type-assertions: true
    check-blank: true
linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - revive
